FROM oven/bun:alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and bun.lockb
COPY ./package.json ./bun.lock ./

# Install dependencies
RUN bun install --frozen-lockfile --ignore-scripts

COPY . .

RUN bun run build

# Copy the rest of the application code

FROM caddy:2.10-alpine

WORKDIR /app

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/dist/public /usr/share/caddy

EXPOSE 3000/tcp

#CMD ["ls", "-la"]
